# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: X
  demands:
   - agent.name -equals X


steps:
- script: sudo -s &&\
          curl -sSL https://get.docker.com/ | sh && \
          git clone https://github.com/CAESAR269/Springboot-Monolithic.git && \
          cd Springboot-Monolithic && \
          

          
          

 